# Generated by Django 5.0.6 on 2024-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='destination_code',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='source_code',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='stops',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('source', 'source_code', 'destination', 'destination_code', 'stops')},
        ),
    ]
