# Generated by Django 5.0.6 on 2024-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_driversinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
