# Generated by Django 5.0.6 on 2024-08-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='stops',
            new_name='route_stops',
        ),
    ]
