# Generated by Django 5.0.6 on 2024-08-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reportimage_classification_reportimage_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportimage',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='reportimage',
            name='confidence',
        ),
    ]
