# Generated by Django 5.0.6 on 2024-08-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_reportimage_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetynotificationreport',
            name='affected_customers',
            field=models.ManyToManyField(blank=True, related_name='safety_alerts', to='home.customers'),
        ),
    ]
