# Generated by Django 5.0.6 on 2024-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_safetynotificationreport_affected_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
