# Generated by Django 5.0.6 on 2024-08-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_users_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_online',
        ),
        migrations.AddField(
            model_name='users',
            name='loginstatus',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=8),
        ),
    ]
