# Generated by Django 5.0.6 on 2024-08-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_users_is_online_users_loginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.travelreport')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportImage',
        ),
    ]
