# Generated by Django 5.0.6 on 2024-08-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reportphoto_delete_reportimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelreport',
            name='duration',
        ),
    ]
