# Generated by Django 5.0.6 on 2024-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_busschedule_bus_current_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='stops',
            field=models.TextField(blank=True, null=True),
        ),
    ]
