# Generated by Django 5.0.6 on 2024-08-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_busschedule_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='current_schedule',
        ),
        migrations.DeleteModel(
            name='BusSchedule',
        ),
    ]
