# Generated by Django 5.0.6 on 2024-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_bus_current_schedule_delete_busschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True),
        ),
    ]
