# Generated by Django 5.0.6 on 2024-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_travelreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10, null=True),
        ),
    ]
