# Generated by Django 5.0.6 on 2024-09-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_busbooking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='departure_date',
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10, null=True),
        ),
    ]
