# Generated by Django 5.0.6 on 2024-09-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_safetynotificationreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='additional_passengers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
