# Generated by Django 5.0.6 on 2024-09-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_busbooking_additional_passengers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='additional_passengers',
            new_name='passenger_details',
        ),
    ]
