# Generated by Django 5.0.6 on 2024-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bus_schedule_version_busbooking_schedule_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreschedule',
            name='schedule_version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
