# Generated by Django 5.0.6 on 2024-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_agentjob_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentjob',
            name='original_arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentjob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
